### PR TITLE
Support new Google URLs

### PR DESCRIPTION
**Pull request by JeffFessler**
This PR is aimed to address #6 by providing a simple function that just adapts the URL appropriately.  It also supports downloading into an `IO` instead of insisting on a file.

If the functions seem OK, then I'll document them.  For now this is a RFC...

### CODE REVIEW

**Comment by flexagoon** [comment]
Why aren't you using `replace` for the link format method?

**Comment by JeffFessler** [comment]
> Why aren't you using `replace`

Doh, I forgot about it.  I will update.  But first I need to fix the doc build in a separate PR...

**Comment by JeffFessler** [comment]
@sjkelly ok, now it uses `replace`.  Comments?

**Review by sjkelly — APPROVED** [review]
Seems good. It was not clear immediately what was the relevant change. In general it makes it easier for review if you rebase, rather than merge FYI.
Also it is good practice to make commits and changes small and related. There are doc string additions here too.

**Comment by JeffFessler** [comment]
Sorry about my bad git hygiene.  Hopefully someday there will be a rebase button in the gui!  https://github.com/orgs/community/discussions/22281
I will try to figure out a command line rebase in the future.

Just one comment about the docstring though.  I did not actually add a docstring to the function `unshortlink` if that's the one you were mentioning.  If you look at the original code, that docstring was a few blank lines away from the function it was documenting, so had no effect!  I just removed those blank lines.  It's a bit hard to see in the diff.

**Comment by JeffFessler** [comment]
I've updated the README now and I will merge tomorrow unless anyone objects before then.  The merge will show us the updated README and the Docs (hopefully) and then I can refine if needed before releasing 0.2.
Later someone can remove unneeded code if they want,
but at this stage I just want to add, not deprecate.

**Pull request merged**
